services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.3.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - backend
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:11.6.1
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/env
    networks:
      - backend
      - frontend
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  frontend:
  backend:
